In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)

[[[[[1 2 3 4 5]]]]]

In [4]:
arr.ndim

5

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr1 = np.arange(1,11)
arr1 = arr1.reshape(2,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
arr1[1][-1]

np.int64(10)

In [9]:
arr1[1][1:4]

array([7, 8, 9])

In [10]:
arr1.shape

(2, 5)

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
add= arr1 + arr2
print(add)
sub = arr1 - arr2
print(sub)
mul = arr1 * arr2
print(mul)
divide = arr1 / arr2
print(divide)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]

In [16]:
arra = np.array([1,2,3,4,5])
a=np.mean(arra)
b=np.median(arra)
d=np.std(arra)
print(a, b , d)

3.0 3.0 1.4142135623730951

In [18]:
newarr = np.arange(1, 16)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
#reshape
newarr.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

PANDAS

In [20]:
import pandas as pd

In [24]:
df = pd.DataFrame({'name': ['Ajay', 'Vijay', 'Rudra'],
                'course':['CSE', 'AIML', 'ELCE'],
                'age': [18, 19, 21]
                })
print(df)

    name course  age
0   Ajay    CSE   18
1  Vijay   AIML   19
2  Rudra   ELCE   21

In [26]:
df.describe()

             age
count   3.000000
mean   19.333333
std     1.527525
min    18.000000
25%    18.500000
50%    19.000000
75%    20.000000
max    21.000000

In [29]:
list(df.columns)

['name', 'course', 'age']

In [31]:
#accessing a column in dataframe
df['course']

0     CSE
1    AIML
2    ELCE
Name: course, dtype: str

In [35]:
#how to access a row using index
df.iloc[2] = ['Tulip', 'Flower', 1]
df

    name  course  age
0   Ajay     CSE   18
1  Vijay    AIML   19
2  Tulip  Flower    1

In [37]:
df['city']=['Ghaziabad', 'Delhi', 'Germany']
df

    name  course  age       city
0   Ajay     CSE   18  Ghaziabad
1  Vijay    AIML   19      Delhi
2  Tulip  Flower    1    Germany

In [38]:
df = df.drop(0)
df

    name  course  age     city
1  Vijay    AIML   19    Delhi
2  Tulip  Flower    1  Germany

In [41]:
#how to load csv/excel files
newdf = pd.read_csv('sample_students.csv')
newdf

,student_id,name,age,gender,department,year,email,phone,cgpa
0,STU001,Aarav Sharma,19,Male,Computer Science,2,aarav.sharma@example.com,9000000001,8.4
1,STU002,Ananya Verma,20,Female,Information Technology,3,ananya.verma@example.com,9000000002,9.1
2,STU003,Ishaan Gupta,18,Male,Electronics,1,ishaan.gupta@example.com,9000000003,7.8
3,STU004,Diya Singh,21,Female,Mechanical,4,diya.singh@example.com,9000000004,8.7
4,STU005,Vivaan Patel,19,Male,Computer Science,2,vivaan.patel@example.com,9000000005,7.5
5,STU006,Myra Joshi,20,Female,Civil,3,myra.joshi@example.com,9000000006,8.9
6,STU007,Aditya Kumar,18,Male,Information Technology,1,aditya.kumar@example.com,9000000007,7.2
7,STU008,Sara Khan,21,Female,Computer Science,4,sara.khan@example.com,9000000008,9.3
8,STU009,Reyansh Mehta,19,Male,Electrical,2,reyansh.mehta@example.com,9000000009,8.1
9,STU010,Aadhya Rao,20,Female,Electronics,3,aadhya.rao@example.com,9000000010,8.6
10,STU011,Krishna Das,18,Male,Mechanical,1,krishna.das@example.com,9000000011,7.9
11,STU012,Ira Malhotra,21,Female,Information Technology,4,ira.malhotra@example.com,9000000012,9.0
12,STU013,Arjun Nair,19,Male,Civil,2,arjun.nair@example.com,9000000013,7.6
13,STU014,Kiara Kapoor,20,Female,Computer Science,3,kiara.kapoor@example.com,9000000014,8.8
14,STU015,Atharv Mishra,18,Male,Electrical,1,atharv.mishra@example.com,9000000015,7.4
15,STU016,Anvi Reddy,21,Female,Electronics,4,anvi.reddy@example.com,9000000016,9.2
16,STU017,Kabir Chawla,19,Male,Information Technology,2,kabir.chawla@example.com,9000000017,8.0
17,STU018,Meera Iyer,20,Female,Mechanical,3,meera.iyer@example.com,9000000018,8.5
18,STU019,Rudra Sinha,18,Male,Computer Science,1,rudra.sinha@example.com,9000000019,7.7
19,STU020,Saanvi Bansal,21,Female,Civil,4,saanvi.bansal@example.com,9000000020,9.4
20,STU021,Dhruv Arora,19,Male,Electrical,2,dhruv.arora@example.com,9000000021,8.2
21,STU022,Pari Saxena,20,Female,Computer Science,3,pari.saxena@example.com,9000000022,8.7
22,STU023,Yash Thakur,18,Male,Electronics,1,yash.thakur@example.com,9000000023,7.1
23,STU024,Navya Pillai,21,Female,Information Technology,4,navya.pillai@example.com,9000000024,9.1
24,STU025,Atharva Kulkarni,19,Male,Mechanical,2,atharva.kulkarni@example.com,9000000025,8.3
25,STU026,Riya Choudhary,20,Female,Civil,3,riya.choudhary@example.com,9000000026,8.6
26,STU027,Devansh Jain,18,Male,Computer Science,1,devansh.jain@example.com,9000000027,7.3
27,STU028,Tara Bose,21,Female,Electrical,4,tara.bose@example.com,9000000028,9.0
28,STU029,Manav Khanna,19,Male,Information Technology,2,manav.khanna@example.com,9000000029,8.1
29,STU030,Zoya Ali,20,Female,Electronics,3,zoya.ali@example.com,9000000030,8.9
30,STU031,Pranav Kulkarni,18,Male,Civil,1,pranav.kulkarni@example.com,9000000031,7.6
31,STU032,Ishita Roy,21,Female,Computer Science,4,ishita.roy@example.com,9000000032,9.5
32,STU033,Samar Banerjee,19,Male,Mechanical,2,samar.banerjee@example.com,9000000033,8.0
33,STU034,Naina Oberoi,20,Female,Information Technology,3,naina.oberoi@example.com,9000000034,8.4
34,STU035,Om Prakash,18,Male,Electrical,1,om.prakash@example.com,9000000035,7.0
35,STU036,Pihu Desai,21,Female,Electronics,4,pihu.desai@example.com,9000000036,9.2
36,STU037,Kartik Yadav,19,Male,Computer Science,2,kartik.yadav@example.com,9000000037,8.3
37,STU038,Aisha Fernandes,20,Female,Civil,3,aisha.fernandes@example.com,9000000038,8.8
38,STU039,Rohan Bhatia,18,Male,Information Technology,1,rohan.bhatia@example.com,9000000039,7.5
39,STU040,Mahika Sen,21,Female,Mechanical,4,mahika.sen@example.com,9000000040,9.1
40,STU041,Neil D'Souza,19,Male,Electrical,2,neil.dsouza@example.com,9000000041,8.2
41,STU042,Shanaya Ghosh,20,Female,Computer Science,3,shanaya.ghosh@example.com,9000000042,8.6
42,STU043,Ayaan Sheikh,18,Male,Electronics,1,ayaan.sheikh@example.com,9000000043,7.4
43,STU044,Lavanya Menon,21,Female,Information Technology,4,lavanya.menon@example.com,9000000044,9.3
44,STU045,Harsh Vardhan,19,Male,Civil,2,harsh.vardhan@example.com,9000000045,7.9
45,STU046,Samaira Paul,20,Female,Mechanical,3,samaira.paul@example.com,9000000046,8.7
46,STU047,Ritvik Anand,18,Male,Computer Science,1,ritvik.anand@example.com,9000000047,7.8
47,STU048,Aarohi Goyal,21,Female,Electrical,4,aarohi.goyal@example.com,9000000048,9.0
48,STU049,Vihaan Saxena,19,Male,Information Technology,2,vihaan.saxena@example.com,9000000049,8.4
49,STU050,Tanishka Roy,20,Female,Electronics,3,tanishka.roy@example.com,9000000050,8.9