In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv('sales_dataset.csv')
sales

,Order_ID,Order_Date,Customer_Name,Region,Product,Quantity,Unit_Price_INR,Sales_Channel,Order_Status
0,S001,2026-01-03,Aarav Mehta,North,Laptop,1.0,54999.0,Online,Delivered
1,S002,2026/01/04,Priya Sharma,south,Smartphone,2.0,18999.0,Store,Delivered
2,S003,05-01-2026,Rohan Verma,East,Headphones,3.0,1499.0,Online,Shipped
3,S004,2026-01-06,Neha Gupta,West,Monitor,1.0,12999.0,Retail,Pending
4,S005,2026-01-07,Kabir Singh,NORTH,Keyboard,2.0,899.0,Online,Delivered
5,S006,2026-01-08,Ananya Rao,South,Mouse,4.0,499.0,Store,Delivered
6,S007,2026-01-09,Ishaan Patel,East,Tablet,1.0,24999.0,Online,Returned
7,S008,2026-01-10,Meera Joshi,West,Printer,1.0,7999.0,Retail,Shipped
8,S009,2026-01-11,Dev Malhotra,North,USB Drive,5.0,399.0,Online,Delivered
9,S010,2026-01-12,Sara Khan,South,Webcam,2.0,2199.0,Online/Store,Delivered
10,S011,2026-01-13,Arjun Das,East,Laptop,1.0,57999.0,Online,Pending
11,S012,2026-01-14,Tanya Roy,West,Smartphone,1.0,19999.0,Retail,Delivered
12,S013,2026-01-15,Vikram Yadav,North,Headphones,2.0,1599.0,Online,Shipped
13,S014,2026-01-16,Diya Kapoor,South,Monitor,1.0,13999.0,Store,Delivered
14,S015,2026-01-17,Aditya Jain,East,Keyboard,3.0,999.0,Online,Delivered
15,S016,2026-01-18,Pooja Nair,West,Mouse,2.0,549.0,Retail,Pending
16,S017,2026-01-19,Rahul Bose,North,Tablet,1.0,22999.0,Online,Delivered
17,S018,2026-01-20,Ira Sen,South,Printer,1.0,8499.0,Store,Shipped
18,S019,2026-01-21,Manav Gill,East,USB Drive,10.0,three-forty-nine,Online,Delivered
19,S020,2026-01-22,Kavya Reddy,West,Webcam,1.0,2399.0,Retail,Delivered
20,S021,2026-01-23,Nikhil Sinha,North,Laptop,1.0,54999.0,Online,Delivered
21,S022,2026-01-24,Aditi Mishra,South,Smartphone,2.0,18999.0,Store,Shipped
22,S023,2026-01-25,Samar Ali,East,Headphones,1.0,1499.0,Online,Delivered
23,S024,2026-01-26,Riya Chawla,West,Monitor,2.0,12999.0,Retail,Delivered
24,S025,2026-01-27,Yash Thakur,North,Keyboard,1.0,899.0,Online,Pending
25,S026,2026-01-28,Mira Thomas,South,Mouse,3.0,499.0,Store,Delivered
26,S027,2026-01-29,Kunal Bhat,East,Tablet,1.0,24999.0,Online,Shipped
27,S028,2026-01-30,Sana Qureshi,West,Printer,2.0,7999.0,Retail,Delivered
28,S029,2026-01-31,Om Prakash,North,USB Drive,4.0,399.0,Online,Delivered
29,S030,2026-13-01,Leena Dutta,South,Webcam,1.0,2199.0,Store,Returned
30,S031,2026-02-02,Ritwik Ghosh,East,Laptop,1.0,56999.0,Online,Delivered
31,S032,2026-02-03,Naina Arora,West,Smartphone,1.0,20999.0,Retail,Shipped
32,S033,2026-02-04,Harsh Vardhan,North,Headphones,2.0,1599.0,Online,Delivered
33,S034,2026-02-05,Simran Kaur,South,Monitor,1.0,13999.0,Store,Pending
34,S035,2026-02-06,Keshav Iyer,East,Keyboard,2.0,999.0,Online,Delivered
35,S036,2026-02-07,Mahi Bansal,West,Mouse,1.0,549.0,Retail,Delivered
36,S037,2026-02-08,Parth Kulkarni,North,Tablet,1.0,23999.0,Online,Shipped
37,S038,2026-02-09,Zoya Mirza,South,Printer,NaN,8499.0,Store,Delivered
38,S039,2026-02-10,Aman Choudhary,East,USB Drive,6.0,349.0,Online,Delivered
39,S040,2026-02-11,Tara Mukherjee,West,Webcam,2.0,2399.0,Retail,Delivered
40,S041,2026-02-12,Aarav Mehta,north,Laptop,1.0,54999.0,Online,Delivered
41,S042,2026-02-13,Priya Sharma,South,Smart Phone,2.0,18999.0,online,delivered
42,S043,14/02/2026,Rohan Verma,EAST,Headphones,3.0,1499.0,Online,Shipped
43,S044,2026-02-15,Neha Gupta,West,Monitor,0.0,12999.0,Retail,Pending
44,S045,2026-02-16,Kabir Singh,North,Keyboard,-2.0,899.0,Online,Delivered
45,S046,2026-02-17,Ananya Rao,South,Mouse,4.0,NaN,Store,Delivered
46,S047,2026-02-18,Ishaan Patel,Eest,Tablet,1.0,24999.0,Online,In Transit
47,S048,2026-02-19,NaN,West,Printer,1.0,7999.0,Retail,delivered
48,S049,2026-02-20,Dev Malhotra,North,USB Drive,5.0,399.0,Online,Delivered
49,S049,2026-02-21,Sara Khan,South,Webcam,2.0,2199.0,Store,Delivered

In [4]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        50 non-null     str
 1   Order_Date      50 non-null     str
 2   Customer_Name   49 non-null     str
 3   Region          50 non-null     str
 4   Product         50 non-null     str
 5   Quantity        49 non-null     float64
 6   Unit_Price_INR  49 non-null     str
 7   Sales_Channel   50 non-null     str
 8   Order_Status    50 non-null     str
dtypes: float64(1), str(8)
memory usage: 3.6 KB

In [5]:
#checking missing values
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     1
Region            0
Product           0
Quantity          1
Unit_Price_INR    1
Sales_Channel     0
Order_Status      0
dtype: int64

In [6]:
#handling missing values
#2 ways of handling missing data

In [8]:
#1.dropping the rows with missing values
sales = sales.dropna()
sales.shape

(47, 9)

In [9]:
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Region            0
Product           0
Quantity          0
Unit_Price_INR    0
Sales_Channel     0
Order_Status      0
dtype: int64

In [11]:
sales = pd.read_csv('sales_dataset.csv')
sales

,Order_ID,Order_Date,Customer_Name,Region,Product,Quantity,Unit_Price_INR,Sales_Channel,Order_Status
0,S001,2026-01-03,Aarav Mehta,North,Laptop,1.0,54999.0,Online,Delivered
1,S002,2026/01/04,Priya Sharma,south,Smartphone,2.0,18999.0,Store,Delivered
2,S003,05-01-2026,Rohan Verma,East,Headphones,3.0,1499.0,Online,Shipped
3,S004,2026-01-06,Neha Gupta,West,Monitor,1.0,12999.0,Retail,Pending
4,S005,2026-01-07,Kabir Singh,NORTH,Keyboard,2.0,899.0,Online,Delivered
5,S006,2026-01-08,Ananya Rao,South,Mouse,4.0,499.0,Store,Delivered
6,S007,2026-01-09,Ishaan Patel,East,Tablet,1.0,24999.0,Online,Returned
7,S008,2026-01-10,Meera Joshi,West,Printer,1.0,7999.0,Retail,Shipped
8,S009,2026-01-11,Dev Malhotra,North,USB Drive,5.0,399.0,Online,Delivered
9,S010,2026-01-12,Sara Khan,South,Webcam,2.0,2199.0,Online/Store,Delivered
10,S011,2026-01-13,Arjun Das,East,Laptop,1.0,57999.0,Online,Pending
11,S012,2026-01-14,Tanya Roy,West,Smartphone,1.0,19999.0,Retail,Delivered
12,S013,2026-01-15,Vikram Yadav,North,Headphones,2.0,1599.0,Online,Shipped
13,S014,2026-01-16,Diya Kapoor,South,Monitor,1.0,13999.0,Store,Delivered
14,S015,2026-01-17,Aditya Jain,East,Keyboard,3.0,999.0,Online,Delivered
15,S016,2026-01-18,Pooja Nair,West,Mouse,2.0,549.0,Retail,Pending
16,S017,2026-01-19,Rahul Bose,North,Tablet,1.0,22999.0,Online,Delivered
17,S018,2026-01-20,Ira Sen,South,Printer,1.0,8499.0,Store,Shipped
18,S019,2026-01-21,Manav Gill,East,USB Drive,10.0,three-forty-nine,Online,Delivered
19,S020,2026-01-22,Kavya Reddy,West,Webcam,1.0,2399.0,Retail,Delivered
20,S021,2026-01-23,Nikhil Sinha,North,Laptop,1.0,54999.0,Online,Delivered
21,S022,2026-01-24,Aditi Mishra,South,Smartphone,2.0,18999.0,Store,Shipped
22,S023,2026-01-25,Samar Ali,East,Headphones,1.0,1499.0,Online,Delivered
23,S024,2026-01-26,Riya Chawla,West,Monitor,2.0,12999.0,Retail,Delivered
24,S025,2026-01-27,Yash Thakur,North,Keyboard,1.0,899.0,Online,Pending
25,S026,2026-01-28,Mira Thomas,South,Mouse,3.0,499.0,Store,Delivered
26,S027,2026-01-29,Kunal Bhat,East,Tablet,1.0,24999.0,Online,Shipped
27,S028,2026-01-30,Sana Qureshi,West,Printer,2.0,7999.0,Retail,Delivered
28,S029,2026-01-31,Om Prakash,North,USB Drive,4.0,399.0,Online,Delivered
29,S030,2026-13-01,Leena Dutta,South,Webcam,1.0,2199.0,Store,Returned
30,S031,2026-02-02,Ritwik Ghosh,East,Laptop,1.0,56999.0,Online,Delivered
31,S032,2026-02-03,Naina Arora,West,Smartphone,1.0,20999.0,Retail,Shipped
32,S033,2026-02-04,Harsh Vardhan,North,Headphones,2.0,1599.0,Online,Delivered
33,S034,2026-02-05,Simran Kaur,South,Monitor,1.0,13999.0,Store,Pending
34,S035,2026-02-06,Keshav Iyer,East,Keyboard,2.0,999.0,Online,Delivered
35,S036,2026-02-07,Mahi Bansal,West,Mouse,1.0,549.0,Retail,Delivered
36,S037,2026-02-08,Parth Kulkarni,North,Tablet,1.0,23999.0,Online,Shipped
37,S038,2026-02-09,Zoya Mirza,South,Printer,NaN,8499.0,Store,Delivered
38,S039,2026-02-10,Aman Choudhary,East,USB Drive,6.0,349.0,Online,Delivered
39,S040,2026-02-11,Tara Mukherjee,West,Webcam,2.0,2399.0,Retail,Delivered
40,S041,2026-02-12,Aarav Mehta,north,Laptop,1.0,54999.0,Online,Delivered
41,S042,2026-02-13,Priya Sharma,South,Smart Phone,2.0,18999.0,online,delivered
42,S043,14/02/2026,Rohan Verma,EAST,Headphones,3.0,1499.0,Online,Shipped
43,S044,2026-02-15,Neha Gupta,West,Monitor,0.0,12999.0,Retail,Pending
44,S045,2026-02-16,Kabir Singh,North,Keyboard,-2.0,899.0,Online,Delivered
45,S046,2026-02-17,Ananya Rao,South,Mouse,4.0,NaN,Store,Delivered
46,S047,2026-02-18,Ishaan Patel,Eest,Tablet,1.0,24999.0,Online,In Transit
47,S048,2026-02-19,NaN,West,Printer,1.0,7999.0,Retail,delivered
48,S049,2026-02-20,Dev Malhotra,North,USB Drive,5.0,399.0,Online,Delivered
49,S049,2026-02-21,Sara Khan,South,Webcam,2.0,2199.0,Store,Delivered

In [12]:
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     1
Region            0
Product           0
Quantity          1
Unit_Price_INR    1
Sales_Channel     0
Order_Status      0
dtype: int64

In [13]:
sales['Quantity'].mean()

np.float64(1.9795918367346939)

In [14]:
sales['Quantity'].median()

np.float64(1.0)

In [15]:
sales['Quantity']=sales['Quantity'].fillna(2)
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     1
Region            0
Product           0
Quantity          0
Unit_Price_INR    1
Sales_Channel     0
Order_Status      0
dtype: int64

In [16]:
sales['Region'].unique()

<StringArray>
[ 'North',  'south',   'East',   'West',  'NORTH', 'South ',  'South',
  'north',   'EAST',   'Eest']
Length: 10, dtype: str

In [17]:
sales['Region'] = sales['Region'].replace('Noth', 'North' )
sales['Region'] = sales['Region'].replace('EAST', 'East' )
sales['Region'].unique()

<StringArray>
['North', 'south', 'East', 'West', 'NORTH', 'South ', 'South', 'north',
 'Eest']
Length: 9, dtype: str

In [18]:
sales['Region'] = sales['Region'].fillna('North')
sales.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     1
Region            0
Product           0
Quantity          0
Unit_Price_INR    1
Sales_Channel     0
Order_Status      0
dtype: int64

In [26]:
sales.sales.dropna()
sales.shape()

AttributeError: 'DataFrame' object has no attribute 'sales'

In [27]:
sales['Region'].value_counts()

Region
West      12
North     11
East      11
South     11
south      1
NORTH      1
South      1
north      1
Eest       1
Name: count, dtype: int64

In [28]:
sales.duplicated().sum()

np.int64(0)

In [29]:
sales = sales.drop_duplicates()